[project]
name = 'eth-india-stacks'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 3
epoch = 'latest'

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 3
epoch = 'latest'

[contracts.platform-token]
path = 'contracts/platform-token.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
